# ApiError
```
class ApiError extends Error{
    constructor(
        statusCode,
        message="Something went wrong",
        errors = [],
        statck = ""
    ){
        super(message)
        this.statusCode = statusCode;
        this.data = nall
        this.message = message
        this.success = false
        this.errors = errors

        if (statck){
            this.statck = statck
        }else{
            Error.captureStackTrace(this, this.constructor)
        }
    }
}

export {ApiError}
```


# apiResponse

```
class apiResponse {
    constructor(statusCode, data, message="Success"){
        this.statusCode = statusCode
        this.data = data
        this.message = message
        this.success = statusCode < 400
    }
}
```


# asyncHandeler

## Using promices (Recomended)
```
const asyncHandeler = (requestHendaler) => () => {
    (req, res, next) => {
        Promise.resolve(
            requestHendaler(req, res, next)
        ).catch((err) => next(err))
    }
}

export {asyncHandeler}
```

## Using tryCatch
```
const asyncHandeler = (fu) => async (req, res, next) => {
    try {
        await fu(req, res, next)
    } catch (error) {
        res.status(error.code || 500).json({
            sucess: false,
            message: error.message
        })
    }
}
export {asyncHandeler}
```

> Higer class function
1. normal async function
```
const asyncHandeler = async () => {}
```

2. normal async function which is return another function
```
const asyncHandeler = (func) => {
    return () => {}
}
```

3. write this beter way, `return` keyword
```
const asyncHandeler = (func) => {() => {}}
```
4. and we also remove`{}` so now the function look like this:
```
const asyncHandeler = (func) => () => {}
```